import type { Metadata } from 'next';
import { site } from '@/content/site';

/** Default social preview (1200×630), generated by scripts/og-image.mjs. */
export const DEFAULT_OG_IMAGE = { url: '/images/og/parsa-alizadeh.png', width: 1200, height: 630, alt: `${site.name}, software developer` };

interface PageMeta {
  /** Full <title>; not passed through the layout's template. */
  title: string;
  description: string;
  /** Path of the canonical URL, e.g. "/blog/offline-sync". */
  path: string;
  type?: 'website' | 'profile' | 'article';
  image?: { url: string; width?: number; height?: number; alt: string };
  article?: { publishedTime: string; modifiedTime: string; tags: string[]; section: string };
}

/**
 * Complete per-page metadata. Next.js replaces (not merges) the parent's openGraph object,
 * so every page gets the full set: canonical, Open Graph and Twitter card.
 */
export function pageMetadata({ title, description, path, type = 'website', image = DEFAULT_OG_IMAGE, article }: PageMeta): Metadata {
  return {
    title: { absolute: title },
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: site.name,
      locale: 'en_US',
      title,
      description,
      images: [image],
      ...(type === 'profile' ? { firstName: site.firstName, lastName: site.lastName } : {}),
      ...(type === 'article' && article
        ? { publishedTime: article.publishedTime, modifiedTime: article.modifiedTime, authors: [site.name], tags: article.tags, section: article.section }
        : {})
    },
    twitter: { card: 'summary_large_image', title, description, images: [image.url] }
  };
}
